### PR TITLE
Remove Zero-Knowledge part

### PR DESCRIPTION
**Pull request by keyvank**
This commit removes the Zero-Knowledge part of the Groth16 protocol as proposed by @arielgabizon, introducing improvements in both proving-time and memory requirements of the protocol.

Please consult @arielgabizon for security considerations before merging!

### CODE REVIEW

**Comment by keyvank** [comment]
Close for now till `xordemo` test is fixed.

**Comment by keyvank** [comment]
`xordemo` test is fixed, reopening.

**Comment by arielgabizon** [comment]
since the verifier is not changed, security is not an issue

**Comment by whyrusleeping** [comment]
Can we do this? What is the current state?

**Comment by arielgabizon** [comment]
I think so, @keyvank can you add results on how much this increases prover speed?

**Comment by whyrusleeping** [comment]
Cool, in any case, I think it should be made optional. So users can still use this library for proper zero knowledge proofs, and we can turn it off when we just want compression

**Comment by keyvank** [comment]
@arielgabizon Sorry for the delay, difference is like x1.09 for a 130mm circuit

**Comment by keyvank** [comment]
Do you want me to rebase this sometime?

**Comment by porcuquine** [comment]
We are not going to do this now, so I am going to close to reduce noise in the PR queue.

**Pull request closed without merging**
